### ISSUE TITLE
Wrong link for Github

### ISSUE THREAD

**Issue by Brian5600** [csuermann/node-red-contrib-suncron#1]
Hello Cornelius
It seems like You have moved the repositorary to a new place/name. Therefore the link to Github from the Nodered-site and in readme-file is wrong.
Good work and have a nice day.
Best regards 
Brian

**Comment by csuermann** [comment]
Thanks, @Brian5600! Is fixed now :-)

**Comment by Brian5600** [comment]
Thanks, but i is also in the readme-file.
“
Contributions and Suggestions

... are always welcome! Just file a GitHub **issue** or **pull request!**”

**Comment by csuermann** [comment]
Meh, you're right. It has been a long day. Fixed now.
