### ISSUE TITLE
How to easily re-fire events ?

### ISSUE THREAD

**Issue by jirmjos** [csuermann/node-red-contrib-suncron#20]
First my congratulations for this awesome sun events node.
Since I discovered it it has become my go-to node for triggering all my automations based on solar time.
My problem is that I can't find an easy way to force the node to reevaluate and re-fire the corresponding event. 
From the documentation I understand that with simply updating offset or schedules the node should re-evaluate and re-trigger the event but I do not want to update anything, all I want is simply order a manual re-trigger the current event (exactly the same process executed on node start-up if the checked "emit preceding event on startup") but fired from the input flow to node. 
Maybe It could be simply as enabling one additional property in the node if are checked enable "a manual fire" trough an input message like ex. msg.payload = "update" or something so simple.

Best regards
Jose,

**Comment by jirmjos** [comment]
Hi Cornelius,
My goodness ... how fast are you!

Your added feature on v1.5.0 to manually update with any non object payload is working like a charm !!.

Thank you so much. You make my day.
All my respects.
Jose,

**Comment by csuermann** [comment]
My pleasure! Glad to hear it's working like you expected.
