### ISSUE TITLE
Version 1.6.2 suddenly looks different

### ISSUE THREAD

**Issue by almo604** [csuermann/node-red-contrib-suncron#37]
I am kind of unsettled with suncron. Tried version 1.6.2 this morning and has success with injecting sunrise/set times into my flow.
Now I wanted to again manage my palettes and tried to re-install 1.6.2 but got what you can see in the enclosed pic.

How to set the location? No choice for payload. 

Am I completely misunderstanding what’s going on there?

Sorry for my bad English

Brgds
Aloism604

scrennshot:

![2024-06-01_10-48-35](https://github.com/csuermann/node-red-contrib-suncron/assets/34207096/ea1c32ca-6cfb-4500-8956-3787a79bf531)

**Comment by csuermann** [comment]
Are you sure you didn't install a fork of my original suncron package? The Node-RED catalogue [shows at least 2 packages](https://flows.nodered.org/search?term=suncron) and your screenshot seems to be referring to the other one?!

**Comment by almo604** [comment]
Hi Cornelius,

 

Let me recap what I did.

 

-          I was looking at the PresenceFaker node and found a related node to implement the sun status: suncron

-          A link on the PresenceFaker node to suncron example (https://gist.github.com/csuermann/604f846f4b7bc3a518dc6385c16e3a48) led to a nonexistent page.

-          In node-red I tried the palette-manager and found two instances of suncron: Ver: 1.6.2 and 2.1.4. Both with the same description. If possible, I usually install the latest version (= 2.1.4). So I installed 2.1.4.

-          With this version I had problems running a flow together with a function to convert the time values into windows-start and windows-end. (There are some example in the net, with such flows.)

-          This led me to writing you my first letter on how to form a payload message.

-          In the meantime I was trying to de-install 2.1.6 and install 1.6.2. Had some troubles but finally succeeded and installed 1.6.2.

-          Somehow, during installing and removing both packages back and forth, I obviously ended up in having both version (or at least some parts of it) in node-red. 

-          That must have been the reason to the screen shot I sent you.

-          With Ver: 1.6.2 I have been lucky to get some results, in what I wanted to achieve.

 

I tried to be as exact as possible in my summary, but might have missed something?

 

Thank you very much for your effort to help me out and solve my problems. Please keep up with you wonderful work.

 

Brgds from Vienna

Aloism604

**Comment by csuermann** [comment]
Thanks for reporting back and for your kind words.
