### ISSUE TITLE
Events dont seem to be firing

### ISSUE THREAD

**Issue by vertex-github** [csuermann/node-red-contrib-suncron#4]
Perhaps this is a user error - but Ive got two Suncron nodes configured to fire events for most of the options, one set on time and one set -15 minutes adjusted.  The output of both suncron nodes is tied to a debug node.  Im not seeing anything emitted from the suncron nodes (and I havent for the last 3 days) except on initial startup or a node red restart.  Am I misunderstanding what this node is supposed to do, or should I be seeing a steady stream of messages fired at each solar event?

**Comment by ahartman** [comment]
I have been using this node for many months and it fires reliably for reach solar event for which you defined a payload. And of course you need to set altitude and longitude for the node to do the necessary calculations.
Please find attached the flow of my working node.

[flows.json.zip](https://github.com/csuermann/node-red-contrib-suncron/files/3999792/flows.json.zip)

**Comment by csuermann** [comment]
@vertex-github, which versions of Node-RED and Suncron are you using? Also, would you mind sharing relevant parts of your flow?

**Comment by csuermann** [comment]
closing due to lack of further information.

**Comment by balthisar** [comment]
I know this is closed, but for the sake of Google searchers, @ahartman's seems to be correct: it's not enough to have a topic; it seems that a payload is required in order to have the events fire.

**Comment by csuermann** [comment]
correct, as also stated in the readme.md: "The schedule contains only events which have been configured with a payload."
