### ISSUE TITLE
Adjustable offset

### ISSUE THREAD

**Issue by chrisg2003** [csuermann/node-red-contrib-suncron#6]
Hi

Thank you for a great node.

Is it possible to somehow use a variable offset to the programmed times. My usage case switches on lights before sunset but as the days grow longer it would be an advantage to be able to easily allow users to adjust the offset via the Dashboard.

Many thanks

**Comment by csuermann** [comment]
Hi @chrisg2003,

Thanks for the feature request, which I just published as part of v.1.3.2.

The offsets can now be overwritten at runtime by passing a config object as msg.payload to the suncron node. All attributes are optional. Offsets need to be expressed in seconds as positive or negative integer values. The below example adjusts the offset for the dusk event to -2 minutes and all others to 0 seconds.

```
{
    "sunrise": 0,
    "sunriseEnd": 0,
    "goldenHourEnd": 0,
    "solarNoon": 0,
    "goldenHour": 0,
    "sunsetStart": 0,
    "sunset": 0,
    "dusk": -120,
    "nauticalDusk": 0,
    "night": 0,
    "nadir": 0,
    "nightEnd": 0,
    "nauticalDawn": 0,
    "dawn": 0
}
```

**Comment by chrisg2003** [comment]
Hi

Many thanks for making the change I look forward to using it.

Chris
