### ISSUE TITLE
event times sent just after daily calculation at midnight

### ISSUE THREAD

**Issue by juntiedt2** [csuermann/node-red-contrib-suncron#7]
it would be nice to get a message just after calculation at midnight with the the resulting event times for the day. This would allow to display these times in dashboard before the actual event is fired up.

**Comment by csuermann** [comment]
Thank you for the suggestion, @juntiedt2!

I just released an update, which I hope will meet your requirements.

<img width="559" alt="suncron config screen" src="https://user-images.githubusercontent.com/10939809/82546515-7f191900-9b58-11ea-9eb3-dfbf11d1d415.png">

Have a nice day!
C.

**Comment by juntiedt2** [comment]
Hi Cornelius,

many thanks for the update.

Looks very good.

Will test it immediately.

regards 

Hannes

 

 

Von: Cornelius Suermann <notifications@github.com> 
Gesendet: Donnerstag, 21. Mai 2020 11:46
An: csuermann/node-red-contrib-suncron <node-red-contrib-suncron@noreply.github.com>
Cc: juntiedt2 <johannes@untiedt.net>; Mention <mention@noreply.github.com>
Betreff: Re: [csuermann/node-red-contrib-suncron] event times sent just after daily calculation at midnight (#7)

 

Thank you for the suggestion, @juntiedt2 <https://github.com/juntiedt2> !

I just released an update, which I hope will meet your requirements.

 <https://user-images.githubusercontent.com/10939809/82546515-7f191900-9b58-11ea-9eb3-dfbf11d1d415.png> 

Have a nice day!
C.
